### ISSUE TITLE
restart when app code changes

### ISSUE THREAD

**Issue by doubletaketech** [coreybutler/node-windows#124]
I'm new to node-windows and have a question.
if I make a code change to the app's script and save it, why do I have to restart the service for it to take effect?

Thanks,
Donnie

**Comment by coreybutler** [comment]
The technical reason there is no autorestart on code changes is because node-windows isn't monitoring the file system for scripts. This is not something node does automatically, nor do most daemons/background services. It's left as a choice for the application developer.

If you really want to restart the service when a script changes, the node `fs` module has a file watcher. You can use this to restart your application. Alternatively, there are modules like chokidar to do the same.

P.S. Please use gitter for questions in the future.
