### ISSUE TITLE
Using Node Express, source dir

### ISSUE THREAD

**Issue by jasonwmatteson** [coreybutler/node-windows#125]
First, I love this module!  Thanks for all the hard work!

I noticed that using the service, Express seems to want to find the views in a  "C:\Windows\system32\views" folder.

Here is the actual Express error:

"Error: Failed to lookup view "player.ejs" in views directory "C:\Windows\system32\views""

Did I miss something in my config perhaps?  Or do I have to absolute path all of my folders (which would be a pain)?

**Comment by LsKs** [comment]
When you open anything as administrator in Windows, by default it points to "C:\Windows\system32" (try running cmd.exe as administrator). This means that when you install your Express server as a service, it is pointing to that default path.

My way of solving those relative paths is to change the Node's working directory at the application start by:
`process.chdir(__dirname);`

You can check the current working directory in Node using `process.cwd();`

**Comment by coreybutler** [comment]
@jasonwmatteson - @LsKs is correct and has provided a pretty good workaround, though you may have more mileage with `process.cwd()` than `__dirname` (depends on the app). 

Another option, depending on your Express configuration, is to modify the template root configuration. It's been awhile since I used Express, but I'm pretty sure the template system will handle the path resolution whenever you render a template (as long as you give it a root).

Since this isn't really an bug, I'm going to close it. However; feel free to hit me up on Gitter or StackOverflow to carry on the conversation if these suggestions don't work out.
