### ISSUE TITLE
Log Files in Daemon Folder

### ISSUE THREAD

**Issue by forensicsguy20012004** [coreybutler/node-windows#127]
If possible, is there a way to cycle out the three different logs [wrapper.log; out.log; err.log] on a daily basis? If there is, I must have missed it..if this is possible please point me to the proper documentation...if it does not exist could this be an additional feature?

**Comment by coreybutler** [comment]
There's nothing specifically built into node-windows for this, since it defers logging to the OS.

I believe this is something that can be configured in the operating system event log, but I'm not 100% sure which versions of Windows support it. The [event log docs](https://msdn.microsoft.com/en-us/library/windows/desktop/aa385780%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) for your version of Windows is probably the best place to start.
