### ISSUE TITLE
Would you add nodemon script instead of direct node, in case of node crash or code change nodemon restarts

### ISSUE THREAD

**Issue by seddik** [coreybutler/node-windows#147]

**Comment by coreybutler** [comment]
I don't think I understand the question. Are you asking for advice or for a change to the node-windows library?

**Comment by mslaraba** [comment]
when you do this the service runs `node [script]`
I want to be able to use `nodemon [script]` instead
so the ability to execute a diffirent command other than "node" or the ability to use directly the [npm start] in package .json

![image](https://cloud.githubusercontent.com/assets/6674347/21147351/00f61978-c155-11e6-958f-071807c1a5fb.png)

**Comment by coreybutler** [comment]
Have you tried adding the `execPath` attribute to the service? You can specify another executable this way. See [the code](https://github.com/coreybutler/node-windows/blob/master/lib/daemon.js#L339) for details.

**Comment by bernardoadc** [comment]
@coreybutler I actually used execPath with "nodemon", but it didn't worked (and weirdly the xml came out with executable and not execPath):

```
<service>
	<id>nodeetlhubsuban.exe</id>
        ...
	<executable>C:\node\nodejs\node.exe</executable>
```

Not sure why tough, the code seems write. I altered the xml directly, and the service used that info correctly, but somehow it didn't work.

```
<service>
	<id>nodeetlhubsuban.exe</id>
        ...
	<executable>nodemon</executable>
```

The problem seems to be the wrapper. Node has to call nodemon, that calls wrapper, that calls the script. Seems quite complex. If order was swapped (which seems more natural), then you will have to think about how to deal with nodemon vs child_process.fork (maybe they compete each other?)

In the end, it worked using the whole command that npm uses internally, without your wrapper:

```
	<executable>C:\node\nodejs\node.exe</executable>
	<logmode>rotate</logmode>
	<argument>C:\node\npm-global\node_modules\nodemon\bin\nodemon.js</argument>
	<argument>--watch</argument>
	<argument>./ETL</argument>
	<argument>./ETL</argument>
```

**Comment by coreybutler** [comment]
The executable configuration option is designed to replace only the node.exe executable. It's not designed to have a wrapper command, which is ultimately what nodemon is doing. Furthermore, there is a bit of a conflict between nodemon and this library. Noddemon watches directories to restart services, whereas node-windows restarts upon crashes/shutdowns.

Nodemon can be a useful tool for development, but it's not appropriate for a production release. node-windows focuses on production releases. The tool is designed to execute script files as a daemon, not commands as a daemon... so I don't think this is something node-windows should support. However; it's cool to see how @bernardoadc worked around this to make it work.

**Comment by bernardoadc** [comment]
>  Furthermore, there is a bit of a conflict between nodemon and this library. Noddemon watches directories to restart services, whereas node-windows restarts upon crashes/shutdowns.

Yes, I feel the same. I think maybe they should not be integrated. In that regard, maybe would be better to add the feature of watching directories and files directly in node-windows. That wouldn't be hard at all using chokidar and one config property. I can submit a PR with you're interested.

> Nodemon can be a useful tool for development, but it's not appropriate for a production release

You're right, nodemon is primarily for development, and nowadays pm2 for production. However, in some scenarios (like mine, whithout full server permissions) that is trickier, and it's better to deploy projects one by one in their own services. For that nodemon/forever are useful. But I still prefer to include some functionality inside node-windows itself.

> ...worked around this to make it work.

I've actually forgot to point another line that made a big difference:

```
	<workingdirectory>drive:\path\to\project</workingdirectory>
```

This was set to the daemon itself, and nodemon wasn't starting correctly.


Thanks for the tool! Cheers

**Comment by coreybutler** [comment]
@bernardoadc - adding chokidar is a significant extra dependency and beyond the scope of this project. Remember, node-windows maintains the same API as node-mac and node-linux, so anything added to this library needs to be added to all of them. File system monitoring is not something that a background service/daemon manager should be handling anyway, because a production service/daemon should not have changing files. If the application itself needs that, the app could include chokidar and restart itself using this API... but that functionality should be app-specific.

This utility is an _alternative_ for pm2 and _forever_. Those are solid libraries, but they recreate the wheel. Operating systems have had the native ability to run & monitor background services/daemons since well before Node existed. This library is just a bridge to use that native functionality.

The output of this tool intentionally has no dependency on npm and will remain that way. The entire point is to encapsulate everything into standalone executables so programs execute in a predictable manner. Supporting `npm start` or any `npm run` operations defeats the purpose.

**Comment by bernardoadc** [comment]
Sure, I respect that 🙂
