### ISSUE TITLE
Creating `winsw.exe.config` is required to run winws.exe under .NET 4.0 runtime

### ISSUE THREAD

**Issue by kzykhys** [coreybutler/node-windows#17]
Is there any chance to put app.exe.config to `daemon` dir something like this?

```
var svc = new Service({
  name:'Hello World',
  description: 'The nodejs.org example web server.',
  script: 'C:\\path\\to\\helloworld.js',
  supportedRuntime: ['v2.0.50727', 'v4.0]
});
```

or 

```
svn.on('beforeInstall', function () {
    // creates .exe.config
});
```

https://github.com/kohsuke/winsw#net-runtime-40

> Newer versions of Windows (confirmed on Windows Server 2012, possibly with Windows 8, too) do not ship with .NET runtime 2.0, which is what winsw.exe is built against. This is because unlike Java, where a newer runtime can host apps developed against earlier runtime, .NET apps need version specific runtimes.
> 
> One way to deal with this is to ensure that .NET 2.0 runtime is installed through your installer, but another way is to declare that winsw.exe can be hosted on .NET 4.0 runtime by creating an app config file winsw.exe.config.
> 
> ```
> <configuration>
>   <startup>
>     <supportedRuntime version="v2.0.50727" />
>     <supportedRuntime version="v4.0" />
>   </startup>
> </configuration>
> ```

**Comment by arthurblake** [comment]
In my opinion, for simplicity, the extra config file should just always and automatically be generated on install, since there is no real downside to having it (it still works properly in .NET 2.0 environments with or without the file.)

This simplifies node-windows configuration (by not requiring anything extra at all), so it just works out of the box on newer windows systems.

This is the approach I took recently in my fork at https://github.com/arthurblake/node-windows and it's working well for me.
