### ISSUE TITLE
Question -  how are the scripts run?

### ISSUE THREAD

**Issue by BradfordMedeiros** [coreybutler/node-windows#174]
Will investigate when I have the time, but how are the scripts actually run?   Are we looking for node on the path, or elsewhere?  I was using electron-packager/winstaller, and realized that they were calling the actually exes that I had generated, instead of some sort of node instance.  This caused bad behavior. 

Seems like this might be resolved in a different way, or maybe a note made somewhere here?  I imagine a big use case of this is in combination with electron to create full windows applications with the node/html/js setup. 

I realize this might be more electron packagers fault than anything, but maybe not.

**Comment by coreybutler** [comment]
Please see the [Using Node-windows with Electron/NW.js](https://github.com/coreybutler/node-windows/wiki#using-node-windows-with-electronnwjs).

**Comment by yuapple** [comment]
@coreybutler excuse me， After reading the explanation, I am a little confused. My business scenario is to start a service in electron, and also to run the application on the desktop. Because some functions in my application require system permissions to implement, I want to open a new process to resolve it
