### ISSUE TITLE
WorkingDirectory Fix

### ISSUE THREAD

**Issue by JoseIgnacio92** [coreybutler/node-windows#225]
Hello!

I found an error that does not allow to correctly pass the workingDirectory parameter.
I was able to solve the problem by editing the file daemon.js line 415

![image](https://user-images.githubusercontent.com/19535530/48714170-db604d00-ebf0-11e8-8971-3e29bcebaede.png)

Regards!

**Comment by xxsoadxx** [comment]
Same issue, Great Fix!!

**Comment by dustingraham** [comment]
I didn't want to alter the vendor file because I was running npm install/npm ci on multiple locations with package-lock.json

I figured out a way to work around this.

```
const svc = new Service({...});
// Explicitly set the path for the daemon to live.
svc._directory = require('path').join(__dirname, '..');
svc.install();
```

Have not done very intensive testing, but at first glance this seems to put the daemon in the parent directory relative to where the install script is called from. You could certainly pass an absolute path as well.

**Comment by DanielRuf** [comment]
You can use [`patch-package`](https://npmjs.com/patch-package) to apply changes.

**Comment by coreybutler** [comment]
I added this to master. It will go out in the 1.0.0 release.
