### ISSUE TITLE
Interactive services

### ISSUE THREAD

**Issue by kadosh1000** [coreybutler/node-windows#253]
Hi, I need my service to be able to be interactive (for example, open notepad). For that I've understood that SERVICE_INTERACTIVE_PROCESS flag should be added or set.

How can it be done?

**Comment by DavidIzaac** [comment]
Same issue...
`require("child_process").exec("notepad");`
After wrapped this sample line of code as a windows service using node-windows, it does not open the notepad.
Any idea @coreybutler  ?

**Comment by coreybutler** [comment]
This is all done with Child Process. Take a look at [this stackoverflow answer](https://stackoverflow.com/a/55138188/720822).

The `SERVICE_INTERACTIVE_PROCESS` is a C# flag that can be set when creating a service... not my area of expertise. node-windows uses winsw under the hood, so you may want to start your search there.

Closing since this seems to be application-specific, not necessarily a node-windows issue.
