### ISSUE TITLE
Needs windows restart before creating service

### ISSUE THREAD

**Issue by amar02041988** [coreybutler/node-windows#343]
I have used node-windows to create a windows service for a node.js based cron application. 
Before running my js code in which node-windows is used to create a service, I always need to first restart the computer, only then the service is getting created and visible in windows service manager.

Is there any issue due to which it needs a computer restart before running node-windows code to create windows service.
Is there any association between windows restart and the node-windows package.

Please let me know.

**Comment by coreybutler** [comment]
node-windows is just a service runner, so there isn't any functionality related to system restarts. If you use node-windows to install a script, you may need to write additional code to have it autostart once the system has booted up. See https://github.com/coreybutler/node-windows/discussions/347.

I'm closing this because the aforementioned discussion is a better forum for this.
